version: '2'

services:
  tweets-location:
    build: ./
    ports:
      - "80:80"
      - "8081:80"
    environment:
      DB_HOST: "mysql"
      DB_PORT: "3306"
      DB_DATABASE: "mydb_tweets"
      DB_USERNAME: "root"
      DB_PASSWORD: "my-secret-pw"
    volumes:
      - "./:/var/www/"
    links:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      MYSQL_DATABASE: "mydb_tweets"
      MYSQL_ROOT_PASSWORD: "my-secret-pw"
    links:
      - mysql:db

  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: "mydb_tweets"
      MYSQL_ROOT_PASSWORD: "my-secret-pw"
    volumes:
      - ~/.data/mysql/tweets:/var/lib/mysql
